### ISSUE TITLE
Webcamoid won't start KDE Neon

### ISSUE THREAD

**Issue by rstreeter** [webcamoid/webcamoid#176]
After running the Run installer I clicked launch now and the app icon showed up then quickly disappeared then I tried launching it from the app menu 
got the same results. I then opened a terminal and dropped the binary in and got this: qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: linuxfb, minimal, offscreen, vnc, xcb.

Aborted

I did the same with the appimage and got the same results.

I have tried the appimage version as well and the same results.

*** Webcamoid information:** Version 8.6.1 (x86_64) The Run insataller

Operating System: KDE neon 5.15
KDE Plasma Version: 5.15.4
KDE Frameworks Version: 5.56.0
Qt Version: 5.12.0
Kernel Version: 4.15.0-47-generic
OS Type: 64-bit
Processors: 4 × Intel® Core™ i5-3317U CPU @ 1.70GHz
Memory: 7.6 GiB of RAM

**Comment by hipersayanX** [comment]
What distribution?

**Comment by rstreeter** [comment]
KDE Neon is the distro it is based on Ubuntu 18.04

**Comment by asmerovski** [comment]
I also have the same issue on KDE Neon.
DISTRIB_ID=neon
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="KDE neon User Edition 5.15"

**Comment by eyalsh** [comment]
Similar issue on Ubuntu 16.04

Installed by running webcamoid-installer-8.6.1-x86_64.run

eyalsh@arthur:~/webcamoid$ ./webcamoid.sh
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: linuxfb, minimal, offscreen, vnc, xcb.

Aborted (core dumped)

**Comment by hipersayanX** [comment]
Tested with Webcamoid daily in all 3 flavors of the distro and everything working well.

**Comment by timwaters** [comment]
I had to run `sudo apt install libxcb-xinerama0` on Ubuntu 16.04
