### ISSUE TITLE
Mac build failed

### ISSUE THREAD

**Issue by terronymous-boosh** [webcamoid/webcamoid#222]
# Reporting a problem? Yes

## Summary

Following the instructions here: https://github.com/webcamoid/webcamoid/wiki/Build-and-install-in-Mac

**Install HomeBrew** [ok] - this automatically pulled down Xcode command line tools

**Install Dependencies** [failed]
I tried to use the provided install_deps.sh script during the preparation phase (downloaded the script; chmod 755 install_deps.sh ; ./install_deps.sh), which runs but doesn't appear to do anything. Where should this be run from? Are there arguments that need to be passed to it?

Instead I looked at the macOS relevant lines and ran them manually. Most worked (installed ffmpeg, gstreamer etc), except the last section:

```
qtIFW=QtInstallerFramework-mac-x64.dmg
    # Install Qt Installer Framework
    ${DOWNLOAD_CMD} http://download.qt.io/official_releases/qt-installer-framework/${QTIFWVER}/${qtIFW} || true

    if [ -e "${qtIFW}" ]; then
        hdiutil convert ${qtIFW} -format UDZO -o qtifw
        7z x -oqtifw qtifw.dmg -bb
        7z x -oqtifw qtifw/5.hfsx -bb
        chmod +x qtifw/QtInstallerFramework-mac-x64/QtInstallerFramework-mac-x64.app/Contents/MacOS/QtInstallerFramework-mac-x64

        qtifw/QtInstallerFramework-mac-x64/QtInstallerFramework-mac-x64.app/Contents/MacOS/QtInstallerFramework-mac-x64 \
            ${qtIinstallerVerbose} \
            --script "$PWD/ports/ci/travis/qtifw_non_interactive_install.qs" \
            --no-force-installations
    fi
fi
```

So instead I installed from here: https://download.qt.io/official_releases/qt-installer-framework/3.2.0/
using a .dmg file

**Install Qt Creator** [failed]
Instructions need updating - I needed to use: 

`brew install homebrew/cask/qt-creator`

Then followed instructions through the end - and lastly clicked on Build button.

This completed with a couple of warnings (presumably non-fatal).

## Current Behavior

I then used the Python build command to create a deployment .dmg file - which I installed. When running webcamoid I can select the source cameras on my Mac (face time camera, Microsoft Lifecam HD - which show their light to indicate that they are selected) however nothing is ever displayed on the screen. It's worth noting that on the configuration tab, there is nothing under video output (e.g. I cannot select ffmpeg)

## Expected Behavior

I was expecting to see my face!

## Steps to Reproduce

Re-open webcamoid. 

## Your Environment

* Webcamoid information: (8.7.1) (x86_64)
* Operating System information: macOS Catalina (10.15.3, Intel x86_64)
* Any other useful information: (logs, gdb backtrace, valgrind logs, screenshots, hardware, etc.)

**Comment by hipersayanX** [comment]
>I tried to use the provided install_deps.sh script during the preparation phase (downloaded the script; chmod 755 install_deps.sh ; ./install_deps.sh), which runs but doesn't appear to do anything. Where should this be run from? Are there arguments that need to be passed to it?

_install_deps.sh_ is not supposed to be run by the user, that file is made with the purpose of being run in Travis CI.
When the documentation points to that script, the idea is to give some guidance to the developer of which dependencies are more or less required to build Webcamoid, and it's made like that because I can't keep changing the documentation every week because some dependency has changed, either by me or by the system, that would be a maintenance hell.

>I then used the Python build command to create a deployment .dmg file - which I installed. When running webcamoid I can select the source cameras on my Mac (face time camera, Microsoft Lifecam HD - which show their light to indicate that they are selected) however nothing is ever displayed on the screen. It's worth noting that on the configuration tab, there is nothing under video output (e.g. I cannot select ffmpeg)

Check that when you compile Webcamoid it gives you [this header](https://travis-ci.org/webcamoid/webcamoid/jobs/653907289#L2078) at the beginning of the build, it will show it once, so you have to remove _webcamoid-build-folder/libAvKys/.qmake.cache_ file if you want to see it again.
Also check that the app folder has a structure similar to [this](https://travis-ci.org/webcamoid/webcamoid/jobs/653907289#L5100).
