### ISSUE TITLE
AAC Support? 

### ISSUE THREAD

**Issue by CTA5816** [webcamoid/webcamoid#243]
I'm trying to upload an mp4 video to Google Drive. Google Drive Help says AAC is the only supported audio codec for uploading files. I can't find AAC in the list of codec options for MP4--am I missing something? If not, are there any codec conversion tools you recommend? 

I don't know much about video file formats, so I would appreciate any background information you can provide!

**Comment by hipersayanX** [comment]
Support for this or that codec or format depends on if FFmpeg was compiled with support for that specific codec or format, if that's the case Webcamoid will pick up it, otherwise it won't.
I don't control that, I don't compile FFmpeg my self, I just pick a prebuilt binary for GNU/Linux, Mac or Windows.
About a 3rd-party converter, idk :man_shrugging:
