### ISSUE TITLE
Not able to stream video through virtual cam in Firefox using Webcamoid in Xubuntu 20.04

### ISSUE THREAD

**Issue by CogitoMax** [webcamoid/webcamoid#335]
# Reporting a problem?

## Summary

Not able to stream video through virtual cam in Firefox using Webcamoid in Xubuntu 20.04

## Current Behavior

Video has been added from "Configure Source" in Webcamoid, but when i test in webcam test sites, it is not getting played, but a blue screen of webcamoid is displayed.
![Screenshot_2020-07-30_15-03-28](https://user-images.githubusercontent.com/68992843/88907591-70489400-d276-11ea-91c0-34e8795e8f37.png)

## Expected Behavior

The video i added should be playing instead of blue webcamoid screen.
![Screenshot_2020-07-30_14-43-45](https://user-images.githubusercontent.com/68992843/88907633-7a6a9280-d276-11ea-8fdf-4ea8ea6aa956.png)

## Steps to Reproduce

There is no option to select the video to play. Edit option is greyed-out/disabled in the screen. 
![Screenshot_2020-07-30_15-07-26](https://user-images.githubusercontent.com/68992843/88907761-a554e680-d276-11ea-8944-55f37e29014a.png)

## Suggestions and tips

General options screen grab is attached, where i think everything is in order.
![Screenshot_2020-07-30_14-52-45](https://user-images.githubusercontent.com/68992843/88907866-c61d3c00-d276-11ea-901c-b20f4b688351.png)

## Your Environment

* Webcamoid information: 8.7.1
* Operating System information: Xubuntu 20.04

# Questions and other matters?

Why the videoplayblack stream is not able to broadcast in webcast tests in Firefox ?

**Comment by CogitoMax** [comment]
Hello,

I am using the daily build now.
But, the video which i have added is not getting played in output in virtual camera mode.
Here is screenshot of preferences :
![1](https://user-images.githubusercontent.com/68992843/95196965-77e86400-07f6-11eb-83d0-e8d63bbb833f.png)

I have tried using webcam tests using various browsers and also in Cheese. 
The output shown is : 
![2](https://user-images.githubusercontent.com/68992843/95197072-a403e500-07f6-11eb-9674-ab64138bee37.png)

Whereas, the video i am playing is 
![3](https://user-images.githubusercontent.com/68992843/95197187-da416480-07f6-11eb-8282-90ad596e3967.png)


Why is the program not playing the above video ?

Any how to or help to play video using virtual camera for linux will be much appreciated. 

Thanks!

**Comment by hipersayanX** [comment]
The virtual camera seems to be working fine, check in _Video/Outputs_ if the virtual camera is selected.

**Comment by CogitoMax** [comment]
In Video/Outputs, Virtual camera is selected. 
![Output](https://user-images.githubusercontent.com/68992843/95823887-09525b80-0d4c-11eb-9c50-6cbc07fe31a6.png)
![Uploading Output1.png…]()

But, it seems that

**Comment by CogitoMax** [comment]
the \

**Comment by hipersayanX** [comment]
There is something totally wrong with what you are doing, in the [2nd capture](https://github.com/webcamoid/webcamoid/issues/335#issuecomment-704212821) you show akvcam clearly working under Cheese  and Webcamoid being detecting it in the 3rd and next captures, but the editor is showing that the file can't be found, it that were the case the virtual camera won't be working from very beginning.
Also, why are you using Wine Notepad to edit a file system instead of using a regular GNU/Linux text editor? GNU/Linux noob? :smile:

**Comment by CogitoMax** [comment]
Hi!
I am a complete noob to Linux :) and i am using Xubuntu xfce environment (20.04). I didn't modify anything. I guess the notepad looks like this by default in xfce.

Will try to reinstall akvcam from the scratch.

I tried uninstalling akvcam as per the commands stated [here](https://github.com/webcamoid/akvcam/wiki/Build-and-install)
But, it didn't remove the akvcam folder inside /etc/


Just an update though, when i changed the Virtual Camera Driver to v4l2loopback, it works fine in Firefox now, but not in Chrome.

**Comment by hipersayanX** [comment]
>I am a complete noob to Linux :)

Ha, I knew it! also welcome to the land :smile: 

>and i am using Xubuntu xfce environment (20.04). I didn't modify anything. I guess the notepad looks like this by default in xfce.

You probably installed Wine recently and the installer configured Wine notepad as the default editor, I don't know Xfce but check in the file properties (or similar option) and select gedit, leafpad or any other more suitable editor.

>Will try to reinstall akvcam from the scratch.

No, is not necessary. The "could not be found " message above is because the file has 600 permissions, that is the file is only readable by the root user (thing that have not much sense anyways, I've updated the wiki), you can read the file with:

 ```
sudo cat /etc/akvcam/config.ini
 ```

>I tried uninstalling akvcam as per the commands stated here
>But, it didn't remove the akvcam folder inside /etc/

The file is created manually, and you must remove manually. .

>Just an update though, when i changed the Virtual Camera Driver to v4l2loopback, it works fine in Firefox now, but not in Chrome.

Because v4l2loopback identifies it self as a M2M device and many programs reject those devices, akvcam instead identifies as a capture device, check the [compatibility list](https://github.com/webcamoid/webcamoid/wiki/Virtual-camera-support#gnulinux).

**Comment by hipersayanX** [comment]
Anyway, seems akvcam is broken again with newer kernels :angry:

**Comment by hipersayanX** [comment]
Problem solved in 9.0.0, closing.
