### ISSUE TITLE
Wrong output camera name in output preferences

### ISSUE THREAD

**Issue by joe-mojo** [webcamoid/webcamoid#378]
# Wrong output camera name in output preferences

## Summary

When going to preferences, then "output", you have a tick with "virtual camera". If you activate it, the select box below allow you to choose an output camera. The bug is that I can choose only capture camera in this list !

## Current Behavior

In the select box where you can select the output device, only a *capture* device is shown.

## Expected Behavior

In the select box where you can select the output device, only a *output* devices should be shown.

## Steps to Reproduce

If Webcamoid crashed, try to reproduce the crash several times to be sure where is the problem. Write the steps to reproduce the issue bellow:

1.  go to preferences
2.  select "output" on the left pane
3.  tick virtual camera on the right pane
4.  the select box with devices is now selectable, but I can see only my capture device. I know it because the /dev/videoX has the X corresponding to capture, and selecting it freeze webcamoid

## Your Environment

* Webcamoid (portable) 8.7.1 with Qt 5.12.3
* Ubuntu 20.04.1 (linux 5.4.0-53-generic)

akvcam is installed and working fine. I'm able to send video to my output device on `/dev/video9` with `ffmpeg` and see it with `ffplay` on `/dev/video7` that is my capture device. When not running ffmpeg, `ffplay /dev/video7` is showing the configured default picture as expected. As you guessed it, my akvcam config has the connection `/dev/video9 --> /dev/video7`

Sadly, only `/dev/video7` is showing in webcamoid output preferences. 

Though webcamoid is writing video with fancy effects through the right output device, seeing the capture device name in output preferences is misleading.

**Comment by hipersayanX** [comment]
This is made like that by design, since the a driver works as an split device and most users won't understand the relation between the output and the capture device, or basically most of them are not supposed to be skilled with computers, and because most of them will expect to just select the device were they want to output the video, I decided to just show the capture device, then Webcamoid will find to which output device its connected and send the stream there.
Webcamoid is designed to be (or supposed to be) the right balance between easy to understand by computer illiterates and powerful enough for computer literates :balance_scale:
