### ISSUE TITLE
Looking for a way to contact you

### ISSUE THREAD

**Issue by quentinlamamy** [webcamoid/webcamoid#388]
Hi, i'm a pro FOSS ( enough to be mozilla reps ^^ )
For one of my project i need to build a soft to replace the closed source one packed with a scanner. I try lot of thing with ffmpeg but i don't succeed to have the expected bahavior in resolution and framerate. Your software succeed doing this. Is there a way ton contact you to discuss about how you succeed in that ?

**Comment by hipersayanX** [comment]
You can check the source of [capturev4l2.cpp](https://github.com/webcamoid/webcamoid/blob/master/libAvKys/Plugins/VideoCapture/src/v4l2sys/src/capturev4l2.cpp) (or the the source code for any of the other submodules). Beside that, Webcamoid tends to be very lax when detecting the devices, that's why Webcamoid can play some devices even when some of their parameters are wrong (for example, when it returns an invalid frame rate).
