### ISSUE TITLE
website shows webcamoid picture even though i cant find it's drivers or the app

### ISSUE THREAD

**Issue by joku0** [webcamoid/webcamoid#455]
I had webcamoid at some point but i deleted it. Now this one website shows this image: 
![image](https://user-images.githubusercontent.com/67695614/132388016-c10475e6-a6af-4237-a38f-4e97bc3337e9.png)
while other websites show my obs virtual camera as i want them to. 
I tried following another thread with a similar problem where i would delete the driver from regedit, but it only showed my obs virtual camera there.
How do i delete webcamoid completelly off my pc?

**Comment by hipersayanX** [comment]
It's all explained in #178, look [here](https://github.com/webcamoid/webcamoid/issues/178#issuecomment-606301900) and [here](https://github.com/webcamoid/webcamoid/issues/178#issuecomment-614857556). Also, I forgot to mention there but you must also delete the virtual camera service, opening an administrator CMD and running:

```
sc delete AkVCamAssistant
```

This gonna be fixed in Webcamoid 9.0.0 for sure.

**Comment by joku0** [comment]
This worked, thanks!
