### ISSUE TITLE
Add QUIT menu item

### ISSUE THREAD

**Issue by jidanni** [webcamoid/webcamoid#503]
Add QUIT menu item... as a convenience.

**Comment by hipersayanX** [comment]
I don't see the point, and I don't want an overloaded UI, just close Webcamoid from the window controls.

**Comment by jidanni** [comment]
Well some users don't get there via so-called window controls. Anyway 99% of the other apps always have a Quit menu item. I mean ctrl-c is a rather rough way to stop a program.

**Comment by hipersayanX** [comment]
Its just clicking the close button or pressing Alt+F4, I don't see any reason to add a redundant  option. Most Android apps doesn't have such options and people still understand how to close them.

![Window controls](https://user-images.githubusercontent.com/1249885/158031227-a7331e60-e4d4-43e1-8a8c-79d0f28a649b.png)

>I mean ctrl-c from a shell is a rather rough way to stop a program, reserved for when something goes wrong.

If the program hags, it won't matter if there are a Quit option in the menu or no, because you will never be able to click it, because the UI is stuck.

**Comment by jidanni** [comment]
Okay, it's a deal ... if this was Android.

Anyway, take your big name browsers, which one would ever forget an explicit exit menu item here on desktop?

**Comment by hipersayanX** [comment]
>Anyway, take your big name browsers, which one would ever forget an explicit exit menu item here on desktop?

But Webcamoid is not a web browser :laughing: . The design vision I have is not the typical desktop app, I want something in the middle that can work in both environments with same code base, keep its UI as simple as possible to target users in both, desktop and mobile. I don't see any reason add an unnecessary repeated option to the menu, for a feature that the operating system already offers for free.
