### ISSUE TITLE
cannot select webcamera anymore

### ISSUE THREAD

**Issue by dchmelik** [webcamoid/webcamoid#569]
## Summary

Can't select webcamera anymore.

## Current Behavior

Chooses built-in webcamera and doesn't let you select another (USB, etc., unless hidden in extremely difficult/slow-to-use/-find  new-/alternative-style menus copied from Apple's & Google's number one top worst design style).

## Expected Behavior

Allow selecting webcamera (like previous versions).

## Your Environment

* Webcamoid information: 9
* Operating System information: Windows 10 x86(-64) (willing to try on UNIX/GNU/Linux if a FreeBSDPackage or Slack(Build|Package))
* Lenovo X1 Yoga ThinkPad, Logitech QuickCam Pro 9000

**Comment by hipersayanX** [comment]
I can't reproduce this issue, all cameras can be detected fine and can be selected, and working.

![Screenshot_20230511_165610](https://github.com/webcamoid/webcamoid/assets/1249885/39236327-bf59-40ac-ae3b-243f00f07278)

Maybe I'm missing context here?

**Comment by dchmelik** [comment]
I see.  Since I was taking photos, not making videos, that's unclear.  Classic (File Edit View Help, etc.) menus are best and clearer.

**Comment by hipersayanX** [comment]
>Classic (File Edit View Help, etc.) menus are best and clearer.

The problem is that traditional menus doesn't fit well in small screens, the best option is using context menus and choosing carefully the design for not overloading the UI, and still having the most important options quickly accessible.

![Screenshot_20230512_175648](https://github.com/webcamoid/webcamoid/assets/1249885/2a7c8808-5ab5-4cec-8d70-3a2f5ffeabf3)
