### ISSUE TITLE
linuxdeployqt

### ISSUE THREAD

**Issue by probonopd** [webcamoid/webcamoid#57]
Hi, I assume you are aware of https://github.com/probonopd/linuxdeployqt but nevertheless wanted to implement it in bash. Would you consider contributing it for others to use, independently of webcamoid?

**Comment by hipersayanX** [comment]
Sure, no problem 😄 it still requires some small adjustments, but I think it will be much better porting the code in Bash to C++, because solving dependencies require a stack that is quite complex to implement in Bash, and my current implementation can solve almost 90% of the dependencies but still need to run once more the get the 10% remaining, because of that.

Also, thanks for AppImage it's quite useful 👍

**Comment by probonopd** [comment]
Thanks @hipersayanX, closing here. The C++ implementation currently also needs 2 runs, would love to have you review its code and possibly suggest what should be ported over from your bash implementation.

**Comment by hipersayanX** [comment]
Yes, no problem, anyway I will be able to review it after Webcamoid 8.0.0 release, I don't want to delay it more.

**Comment by probonopd** [comment]
Is an AppImage available for download somewhere?

**Comment by hipersayanX** [comment]
No yet, it will be available for 8.0.0, hopefully next week.

**Comment by hipersayanX** [comment]
AppImages [are ready](https://github.com/webcamoid/webcamoid/releases/tag/8.0.0), I've compiled in Trusty and tested in newer distros, and worked flawlessly 😄

**Comment by probonopd** [comment]
Thank you very much, added to https://github.com/probonopd/AppImageKit/wiki/AppImages.

**Comment by hipersayanX** [comment]
great!
