### ISSUE TITLE
How would you compare webcamoid with CamTwist?

### ISSUE THREAD

**Issue by theonlygusti** [webcamoid/webcamoid#81]
I wanted to be able to put Desktop video - sources from Applications/whole screen etc. - through streaming services like Skype/Discord/etc.

I originally had a look at webcamoid and then at CamTwist.

I am using CamTwist now as it was very easy to send, for example, single applications through a virtual webcam.

In what ways are webcamoid and CamTwist different though?

**Comment by hipersayanX** [comment]
Let see:

## Source code model and licensing ##

Webcamoid is Free Software licensed under GPLv3+, while CamTwist is proprietary. Both programs are maintained by one unique software developer. But, here is crucial difference, if you watch [CamTwist blog](http://camtwiststudio.com/category/blog/), it stopped updating the program in 2013, then based on the [Twitter account](https://twitter.com/CamTwist), the developer restarted the development 2 years latter, and just to make CamTwist work in newer MacOS versions, and then two more tweets asking for a feature and a new update for new MacOS versions, and you don't even know if hes is really working in that because the development is closed. So the development of that program is carried entirely by that developer, so if he want to stop the development another more year, and you depend on that program you are fucked.

On the other hand, I'm the only one software developer of Webcamoid, but I been received a lot of help from people that helped me a lot for example contributing with [translations](https://hosted.weblate.org/engage/webcamoid/?utm_source=widget), [software packagers](https://repology.org/metapackage/webcamoid), [pull requests](https://github.com/webcamoid/webcamoid/pulls?q=is%3Apr+is%3Aclosed), people [reporting issues](https://github.com/webcamoid/webcamoid/issues), people who take their time to [review](https://www.youtube.com/watch?v=RafjtnBXUR4) Webcamoid, is thanks to all these people that Webcamoid's engine continue working and the community around it growing, also counting 8 years of continuous development in this project, with it's highs and lows, but always planning new things to do. Also the development of Webcamoid is 100% open and transparent, you know in real time what is being worked, and if you want, you can participate in it. And even if I disappear or decide to no continue the project anymore, or the community don't like where the development is going, the community can fork Webcamoid and continue a new development in the way they like.

## Portability ##

CamTwist is written in Objective-C, fully dependent of Xcode, and only works in MacOS. If the developer want to make it work in other platforms, he need to rewrite it entirely  from scratch, in a new programming language and a new IDE. And I did so when ported Webcamoid from [Python to C++](https://github.com/webcamoid/webcamoid/releases/tag/5.0.0) and believe me, it was very painful, lucky I did so when Webcamoid still was not the [monster](https://www.openhub.net/p/Webcamoid/analyses/latest/languages_summary) it is right now.

Webcamoid started as a GNU/Linux program with the vision of making it work in other platforms from the very beginning, then ported to Windows, and one year later (current year) ported to Mac, and every new port made even more easier to port Webcamoid to other platforms, like [FreeBSD](http://webcamoid.github.io/posts/2017/05/16/webcamoid-800-released/), and an [Android port](https://travis-ci.org/webcamoid/webcamoid/jobs/279596394) is ongoing, is just a matter of time before I can write the missing functionality and make it work there.

It may not sound interesting if you don't use those platforms, but if you think carefully supporting more platforms increases the probability of having potential developers helping with the project, more developers helping with the project means more developers fixing bugs, adding new features, leaving to a faster development that may benefit you directly or indirectly. Webcamoid has a higher growing potential than CamTwist, thanks to it's portability.

## Effects ##

I have no idea what effects and how many effects has CamTwist, and this is not much important because all effects that CamTwist has, Webcamoid has or can have easily, and the situation will improve even more with Webcamoid 9.0, when I will introduce scripted plugins, packages and repository support, and API release, putting the development of effects in the hands of the community.

## Interface ##

Let's make it clear, Webcamoid may not have the best looking GUI, but it follow my vision of making the webcam the first class citizen, giving to the webcam the maximum space possible in the GUI, and putting just the minimum necessary controls, so the controls are not very invasive to webcam space. When you open Webcamoid, you see the webcam in all it's glory. Also, the GUI was designed with mobile and small screens in mind from the very beginning, it will require some tweak here and the but not much hard to do.

CamTwist is just a desktop app, it's divided in [two windows](https://www.youtube.com/watch?v=nw4-l1vA11c), one for controls, and one for preview, and the webcam is just an small rectangle in there. You tell me how the developer will port CamTwist to Android and IOS :)

## Features ##

Streamming? Chroma key? Face rig? Don't worry every feature you can think I have already thought about it. One of my ideas in a not so far future is to add support for layouts and profiles, let me explain, right now you have just one unique profile and layout, Webcamoid can show the webcam, or the desktop, or a gif, or a video, so only one stream at time, but with the introduction of layouts will be possible to combine the streams so you will able to combine the webcam and the desktop and make an screen cast, or combine the webcam with a video and make a film review. You will able to create profiles combining a review layout with an effect, let say a banner on the bottom and then you will be able to create a news video. How much time will take this? I don't know, but the idea is there. And growing a community of software developers will be crucial for this.

## Virtual camera and streaming ##

And finally, virtual camera support for Mac, CamTwist has an advantage now, because how I explained [here](https://github.com/webcamoid/webcamoid/wiki/Virtual-camera-support), I can't write a kernel extension because it requires code signing, and that's not possible for me now. But, there are good news, I did a little more research after writing that wiki page, and according to [this](https://github.com/google/santa#kext-signing) is 100% possible to write an open source kernel extension (maybe GPLv3+ too?), and that repository is from Google, so no doubt it's possible. And according to [this](https://stackoverflow.com/questions/6257506/how-much-does-it-cost-to-get-a-code-signing-certificate-from-apple), code sign does doesn't cost that much, and people interested in this could crowd fund it.

Summarizing, Webcamoid is not that much far from it's competitors :)
